**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
arr = np.zeros(10, dtype = np.int32)
arr[4] = 1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [10]:
#Code here
a = int(input("enter a = "))
b = int(input("enter b = "))

arr = np.random.random((a, b))
arr = arr * 100
arr = np.astype(arr, np.int32)
print(arr)
print(np.average(arr))

[[89 47 13]
 [70 39 45]
 [55 11  6]]
41.666666666666664


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [19]:
#Code here

def borderArray(a, b):
    arr = np.zeros((a, b), dtype = np.int32)

    top = arr[0, :]
    right = arr[1:-1, -1]
    bottom = arr[-1, :]
    left = arr[1:-1, 0]

    top += 1
    right += 1
    bottom += 1
    left += 1

    return arr

print(borderArray(4, 4))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [23]:
#Code here
shape = (10, )
array = np.random.uniform(low = np.nextafter(0, 1), high = np.nextafter(1, 0),size = shape)
print(array)

[0.19557172 0.90009218 0.05106922 0.97274409 0.88705662 0.34358778
 0.46824262 0.00105406 0.85463145 0.88886574]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [25]:
#Code here
#can not create as identity matrix of size(3, 4) as they are square matrix

size = 4

arr = np.eye(size)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [27]:
#Code here

shape = (5, 5)

arr = np.random.uniform(low = 0, high = np.nextafter(4, 5), size = shape)

print(arr)

[[3.6228545  0.88655968 2.11489492 3.79186866 1.9576269 ]
 [2.816231   0.2246615  2.98178583 1.16534061 1.36897403]
 [2.17726717 1.70452018 2.20927671 2.53190342 1.9353925 ]
 [3.23328199 1.62645923 2.43931024 0.37345339 3.53747447]
 [2.04341594 1.99256234 1.63021005 3.98879993 0.16967197]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [39]:
#code here

from math import sqrt

shape = (10, 2)
point = np.array([2,3])
arr = np.random.uniform(low = 1, high = np.nextafter(100, 101), size = shape)

def distanceFormAPoint(distance, point):
    n = len(distance)
    result = np.zeros(n, dtype = np.float64)

    for i in range(n):
        pointI = distance[i]

        distanceOfPointI = sqrt((pointI[0] - point[0]) ** 2 + (pointI[1] - point[1]) ** 2)

        result[i] = distanceOfPointI

    return result

print(arr)

print(distanceFormAPoint(distance = arr, point = point))

[[91.74462126 66.489787  ]
 [29.30737068 34.69176644]
 [70.38173721 87.37756696]
 [20.05487885 99.30214686]
 [48.48543609 19.27480171]
 [ 7.12657656 88.97017765]
 [53.85184255 65.17421457]
 [31.81661013 36.49599202]
 [86.74860493 10.7903358 ]
 [87.82642143 74.39895639]]
[109.9320249   41.83372508 108.60771515  97.98000888  49.25205518
  86.12289609  80.9583012   44.84430533  85.10590678 111.64222135]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [47]:
#Code here
shape = (6, 7, 8)
arr = np.zeros(shape = shape)

print(arr[0:1, :, :].size)
print(arr[1:2, 0:6, :-1].size)

56
42


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [59]:
#Code here
input = "1 2 3 4 -8 10"

inputArray = input.split(" ")

# print(inputArray)

inputArray = np.array(inputArray, dtype = np.float64)

inputArray = inputArray[-1::-1]

print(inputArray)

[10. -8.  4.  3.  2.  1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here

def elementCount(array):
    return array.size

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [73]:
#Code here

def softMax(array):
    if(type(array) != np.ndarray):
        raise TypeError(f"{array} is not a ndarray")

    array = np.array(array)

    array = np.exp(array)

    # print(array)

    sum = np.sum(array)

    array = array / sum

    return array

# arr = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
arr = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])

softMax(array = arr)


array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [83]:
#Coder here

def doVStack(*arrays):
    for i in arrays:
        if(type(i) != np.ndarray):
            raise TypeError(f"{i} is not a ndarray")

    array = arrays[0]

    for i in range(1, len(arrays)):
        array = np.vstack((array, arrays[i]))

    return array


a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])


b= np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]]
)

doVStack(a, b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [12]:
#Code here
import numpy as np
def date_array(start, end):
    try:
        startDate = np.datetime64(start)
        endDate = np.datetime64(end)
        # print(startDate + 1)

        result = np.arange(startDate, endDate + 1, 1)

        return result
    except Exception | TypeError as e:
        print(e)

date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [29]:
#code here
def subtractMeanOfEachRowInMatrxi(matrix):
    array = np.array(matrix)
    n = array.shape[0]

    for i in range(n):
        row = array[i, :]
        mean = np.mean(row)

        array[i, :] = row - mean

    return array

arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(subtractMeanOfEachRowInMatrxi(arr))

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [2]:
#Code here

def column_swap(array):
    if(type(array) != np.ndarray):
        if isinstance(array, list):
            array = np.array(array)
        else:
            raise TypeError(f"{array} is not of type ndarray or array");

    n = array.shape[0]

    if(n == 1):
        return array
    temp = array[-1, :].copy()

    array[-1, :] = array[-2, :]
    array[-2, :] = temp

    return array

arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(column_swap(arr))

[[1 2 3]
 [7 8 9]
 [4 5 6]]


###`Q-16:` Replace odd elements in arrays with -1.

In [4]:
#Code here
arr = np.array(arr)
oddValues = arr % 2 != 0

arr[oddValues] = -1

print(arr)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [9]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

result = list()

n = a.size

for i in range(n):
    result.append(int(max(a[i], b[i])))

print(result)

[6, 3, 1, 7, 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here