In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## using np.newaxis to reshape

In [5]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])

a2 = a[: , np.newaxis]
# print(a2)
# print(a2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [9]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])

a2 = np.expand_dims(a, axis = 1)

# print(a2.shape)
# print(a2)
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
fiveUp = a >= 5

# print(a[fiveUp])

fiveDown = a <= 5

# print(a[fiveDown])

# print(a[a % 2 == 0])

c = a[(a > 2) & (a < 11)]

print(c)

# print(fiveUp)

[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


# numpy array vs python list

## speed

In [6]:
from time import time

a = [i for i in range(10000000)]
b = [i for i in range(10000000)]

c = []

startTime = time()

for i in range(len(a)):
    c.append(a[i] + b[i])

endTime = time()

print(endTime - startTime)

8.322850942611694


In [7]:
import numpy as np
a = np.array(a)
b = np.array(b)

startTime = time()

c = a + b

endTime = time()

print(endTime - startTime)

0.9620354175567627


## memory

In [12]:
from sys import getsizeof

a = [i for i in range(10000000)]
print(getsizeof(a))

a = np.array(a, dtype = np.int32)
print(getsizeof(a))


89095160
40000112


# fancy indexing

In [18]:
a = np.arange(24).reshape(6, 4)

# take first, 4th 5th and 6th arrays
print(a[[0, 3, 4, 5]])

[[ 0  1  2  3]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Boolean indexing

In [24]:
a = np.random.randint(0, 100, 24).reshape(6, 4)
print(a)

[[54 53 83 36]
 [83 96 85 12]
 [91 59 59 75]
 [67 61 36 58]
 [79 88 92 32]
 [57 83 37 59]]


In [25]:
a % 2 == 0

array([[ True, False, False,  True],
       [False,  True, False,  True],
       [False, False, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False]])

In [26]:
a[a % 2 == 0]

array([54, 36, 96, 12, 36, 58, 88, 92, 32], dtype=int32)

In [32]:
a[(a > 50) & (a % 2 == 0)]

array([54, 96, 58, 88, 92], dtype=int32)